# -*- coding: utf-8 -*-
from common import *
from content import DESCRIPTIONS
from catalog import TOOLS,GROUPS
import zipfile
DIAGRAM_COUNT=sum(bool(row[5]) for page in PAGES for row in chapter(page,'en'))

def overview(lang):
    t=lambda en,zh:pick(lang,en,zh)
    steps=[('01','PROTOCOL','协议',t('State, consensus and authorization','状态、共识与授权')),('02','MONEY','货币',t('Issuance, custody and monetary ideas','发行、托管与货币理念')),('03','APPLICATION','应用',t('Contracts, stablecoins, DeFi and Web3','合约、稳定币、DeFi 与 Web3')),('04','PRACTICE','实践',t('Compile, deploy locally and verify behavior','编译、本地部署与行为核验'))]
    graphic='<aside class="trust-map" aria-label="'+t('Four views of a blockchain system','区块链系统的四个视角')+'"><div class="map-label">RULES / AUTHORITY / INCENTIVES / CODE</div>'+''.join(f'<div class="map-step"><span>{n}</span><div><strong>{t(en,zh)}</strong><small>{desc}</small></div></div>' for n,en,zh,desc in steps)+'<div class="map-foot">'+t('Understand the rules before signing an action','签署动作前先理解规则')+'</div></aside>'
    body='<section class="hero"><div class="wrap hero-grid"><div><span class="eyebrow">BLOCKCHAIN / CRYPTOCURRENCY / WEB3</span><h1>'+t('Understand the chain<br><em>Build the contract</em>','理解区块链<br><em>构建智能合约</em>')+'</h1><p>'+t('An independent learning atlas for engineers: Bitcoin and Ethereum, monetary sovereignty and Web3, stablecoins and DeFi, Ethereum L2 and Bitcoin Lightning, and a complete Solidity path from first contract to a fixed-supply learning token.','面向工程师的独立学习地图：Bitcoin 与 Ethereum、货币发行权与 Web3、稳定币与 DeFi、Ethereum L2 与 Bitcoin 闪电网络，以及从第一个 Solidity 合约到固定供应学习代币的完整路径。')+'</p><div class="hero-actions"><a class="button" href="'+href('foundations',lang)+'">'+t('Start with the fundamentals →','从基础原理开始 →')+'</a><a class="text-link" href="'+href('practice',lang)+'">'+t('Run the Solidity examples ↗','运行 Solidity 示例 ↗')+'</a></div><div class="hero-meta">21 SECTIONS / '+str(DIAGRAM_COUNT)+' DIAGRAMS / 3 LOCAL LABS<br>'+t('ENGLISH & 中文 · 2 RUNNABLE CONTRACTS · PRIMARY SOURCES','中英双语 · 2 个可运行合约 · 一手资料')+'</div></div>'+graphic+'</div></section><div class="reading wrap">'
    route=[('01',t('Learn the system and the ideas','理解系统及理念'),t('Foundations → History → Money & Web3 → Cryptography → Consensus. Explain what is decentralized, who can issue assets, and what each cryptographic check proves.','原理 → 历史 → 货币与 Web3 → 密码学 → 共识。解释什么去中心化、谁能发行资产，以及密码学检查证明什么。')),('02',t('Follow a transaction','跟踪一笔交易'),t('Bitcoin → Ethereum → Transactions → Contracts. Distinguish a UTXO from account state, token units from ETH, and execution success from finality.','Bitcoin → Ethereum → 交易 → 合约。区分 UTXO 与账户状态、代币单位与 ETH，以及执行成功与最终性。')),('03',t('Create and inspect contract behavior','创建并检查合约行为'),t('Solidity → Create a token → Practice. Compile MessageBoard and StudyToken, deploy on a local EVM and test authorized and rejected operations.','Solidity → 发行代币 → 实践。编译 MessageBoard 与 StudyToken，在本地 EVM 部署，测试授权及拒绝操作。')),('04',t('Analyze applications and dependencies','分析应用及依赖'),t('Stablecoins → DeFi → Scaling & Cross-chain → Applications → Security / Labs. Read rollups, Lightning, interoperability and the dated Web3 snapshot. Map backing, oracles, bridge assumptions, upgrade powers and exit paths.','稳定币 → DeFi → 扩容与跨链 → 应用 → 安全 / 练习，阅读 Rollup、闪电网络、互操作及注明日期的 Web3 进展。画出担保、预言机、桥假设、升级权限与退出路径。'))]
    body+=section('01 / LEARNING ROUTE',t('From concepts to executable behavior','从概念到可执行行为'),t('Assumes basic programming and systems knowledge. The browser exercises need no wallet; the downloadable project uses only a local development chain.','假设具有基本编程及系统知识。浏览器练习无需钱包，下载项目仅使用本地开发链。'),'<div class="sequence">'+''.join(f'<article><span>{n}</span><div><h3>{title}</h3><p>{text}</p></div></article>' for n,title,text in route)+'</div>','route')
    grid='<div class="topic-grid">'+''.join(f'<a class="topic-card" href="{href(page,lang)}"><span class="eyebrow">{i:02} / FIELD NOTES</span><h3>{NAV[lang][i]}</h3><p>{desc[1 if lang=="zh" else 0]}</p></a>' for i,(page,desc) in enumerate(zip(PAGES[1:],DESCRIPTIONS),1))+'</div>'
    body+=section('02 / CHAPTERS',t('Choose a protocol, idea or practical question','选择协议、理念或实践问题'),t('A technical and ideological learning map. Read sequentially or start with the practical question you need.','涵盖技术及理念全景，可以顺序阅读，也可从具体实践问题进入。'),grid,'chapters')
    body+=section('03 / PRACTICE',t('Two contracts and three mechanism labs','两个合约与三项机制练习'),t('Keep concrete evidence of what the code and rules do.','保留代码及规则实际行为的具体证据。'),cards([('SOLIDITY',t('MessageBoard','MessageBoard'),t('Public state, owner-only mutation, an event and a rejected caller.','公开状态、所有者修改、事件及拒绝调用者。')),('ERC-20',t('StudyToken','StudyToken'),t('Fixed supply, transfer, approval and transferFrom without a sale or mint administrator.','固定供应、转账、授权及 transferFrom，无销售或增发管理员。')),('LABS',t('Mechanisms you can inspect','可以观察的机制'),t('Hash links, ordinary allowances and a constant-product AMM quote.','哈希链接、普通授权额度与恒定乘积 AMM 报价。')),('DOWNLOAD',t('A reproducible local project','可复现本地项目'),t('Pinned dependencies, compiler settings, real EVM tests and a complete deployment demo.','固定依赖、编译设置、真实 EVM 测试及完整部署演示。'))]),'practice')
    body+=callout(t('Engineering examples, with explicit scope','具有明确范围的工程示例'),t('Reviewed 1 Oct 2026. No live prices, wallet connection or real-fund transactions are part of this website. The STUDY example creates neither backing nor liquidity. Product interfaces and supported networks can change; code dependencies are pinned for reproduction.','复核于 2026 年 10 月 1 日。本站不提供实时价格、钱包连接或真实资金交易。STUDY 示例不会创建担保或流动性。产品界面与网络支持会变，代码依赖固定以便复现。'))
    return body+'</div>'

def chapter_page(page,lang):
    t=lambda en,zh:pick(lang,en,zh)
    rows=chapter(page,lang);idx=PAGES.index(page)
    anchors=[(r[0],r[1]) for r in rows]
    if page=='scaling':anchors=[('rollups','Ethereum L2'),('lightning',t('Bitcoin Lightning','Bitcoin 闪电网络')),('bridges',t('Bridges & intents','桥与意图')),('updates',t('Recent developments','近期动向')),('dimensions',t('Ecosystem impact','生态影响'))]
    body=hero(lang,page,NAV[lang][idx]+'<br><em>'+t('Rules into practice','从规则到实践')+'</em>',DESCRIPTIONS[idx-1][1 if lang=='zh' else 0],anchors)+'<div class="reading wrap">'
    for i,(ident,title,intro,content,refs,viz) in enumerate(rows,1):body+=section(f'{i:02} / FIELD NOTES',title,intro,(diagram(viz,lang) if viz else '')+content+(cite(lang,*refs) if refs else ''),ident)
    if page in ('bitcoin','ethereum','ideas'):
        anchor='lightning' if page=='bitcoin' else 'rollups' if page=='ethereum' else 'updates'
        body+='<p class="references"><a href="'+href('scaling',lang,anchor)+'">'+t('Continue: L2, Lightning and recent Web3 developments →','继续阅读：L2、闪电网络及近期 Web3 动向 →')+'</a></p>'
    body+=callout(t('Check your understanding','检查理解'),t('For one concrete operation, identify the state, authorization, execution rule, trust dependency and independent evidence that the outcome occurred.','对一项具体操作，指出状态、授权、执行规则、信任依赖及结果确实发生的独立证据。'))
    return body+'</div>'

def tools_page(lang):
    t=lambda en,zh:pick(lang,en,zh)
    body=hero(lang,'tools',t('Choose the right source<br><em>Inspect its scope</em>','选择适用来源<br><em>检查适用范围</em>'),t('A searchable directory of '+str(len(TOOLS))+' primary resources and original tools. Protocol standards, issuer disclosures and developer products answer different questions.','可搜索的 '+str(len(TOOLS))+' 项一手资源及原始工具。协议标准、发行方披露及开发产品回答不同问题。'))+'<div class="reading wrap"><section class="chapter-section">'
    body+='<div class="tool-filter"><label for="tool-search">'+t('Search name, use or limitation','搜索名称、用途或限制')+'</label><input type="search" id="tool-search" placeholder="'+t('e.g. ERC-20, Remix, Web3','例如 ERC-20、Remix、Web3')+'"><label for="tool-category">'+t('Category','类别')+'</label><select id="tool-category"><option value="all">'+t('All categories','所有类别')+'</option>'+''.join(f'<option value="{k}">{v[1 if lang=="zh" else 0]}</option>' for k,v in GROUPS.items())+'</select><p id="tool-count" role="status" aria-live="polite">'+t(str(len(TOOLS))+' resources',str(len(TOOLS))+' 项资源')+'</p></div><div class="tool-grid">'
    for ident,name,url,group,en,zh,limen,limzh in TOOLS:body+=f'<article class="tool-card" data-category="{group}"><span class="eyebrow">{GROUPS[group][1 if lang=="zh" else 0]}</span><h3>{escape(name)}</h3><p>{t(en,zh)}</p><small>{t(limen,limzh)}</small><a href="{url}" target="_blank" rel="noopener noreferrer">'+t('Open original resource ↗','打开原始资源 ↗')+'</a></article>'
    return body+'</div><p id="tool-empty" hidden>'+t('No matching resources. Try another word or category.','无匹配资源，请尝试其他词或类别。')+'</p></section>'+callout(t('Read version and network context','阅读版本与网络上下文'),t('Use the contract examples as a pinned baseline. New documentation can describe newer behavior; issuer-supported chains and public testnets change. Names and tickers are not sufficient to identify a deployment.','以固定合约示例为基线。新文档可能描述更新行为，发行方支持链及公开测试网会改变。名称与简称不足以确定部署身份。'))+'</div>'

def sources_page(lang):
    t=lambda en,zh:pick(lang,en,zh)
    body=hero(lang,'sources',t('Read primary documents<br><em>Compare the assumptions</em>','阅读一手文档<br><em>比较假设</em>'),t('Protocol papers, standards, implementation guides and explicit institutional or issuer perspectives. Sources are linked at the relevant lesson.','协议论文、标准、实现指南及明确的机构 / 发行方视角。相关章节均提供来源链接。'))+'<div class="reading wrap">'
    for i,(group,(en,zh)) in enumerate(GROUPS.items(),1):
        grid='<div class="source-grid">'+''.join(f'<a class="source-card" href="{url}" target="_blank" rel="noopener noreferrer"><span class="eyebrow">{t("ORIGINAL PUBLISHER","原始发布者")}</span><h3>{escape(name)} ↗</h3><p>{t(limen,limzh)}</p></a>' for ident,name,url,g,enq,zhq,limen,limzh in TOOLS if g==group)+'</div>'
        body+=section(f'{i:02} / SOURCES',t(en,zh),t('Read the lesson, then inspect the original rules and deployment context.','先阅读章节，再检查原始规则与部署上下文。'),grid,group)
    body+=callout(t('Keep perspectives and claims separate','分开视角与主张'),t('The Bitcoin proposal, Web3 explanations and BIS monetary perspective have different goals. Tether disclosures describe the issuer’s published arrangements. Read their claims with their scope and date; public code, reserves and legal rights are different evidence types.','Bitcoin 提案、Web3 解释及 BIS 货币视角目标不同。Tether 披露描述发行方发布的安排。阅读时保留范围及日期，公开代码、储备及法律权利是不同证据类型。'))
    return body+'</div>'

def labs_page(lang):
    t=lambda en,zh:pick(lang,en,zh)
    body=hero(lang,'labs',t('Inspect the mechanics<br><em>Change one assumption</em>','观察机制<br><em>改变一项假设</em>'),t('Three local teaching models. No wallet, public RPC, token transfer, upload or saved exercise input. Hashes use browser SHA-256, not Bitcoin serialization or Ethereum Keccak.','三项本地教学模型，无钱包、公开 RPC、代币转移、上传或练习输入保存。哈希使用浏览器 SHA-256，并非 Bitcoin 序列化或 Ethereum Keccak。'),[('chain',t('Hash links','哈希链接')),('allowance',t('Token allowance','代币授权')),('amm',t('AMM quote','AMM 报价'))])+'<div class="reading wrap"><noscript><aside class="callout">'+t('Enable JavaScript for labs; all lesson text and downloads remain available.','启用 JavaScript 使用练习；正文及下载仍可使用。')+'</aside></noscript>'
    def select(ident,label,options):return f'<label for="{ident}">{label}<select id="{ident}">'+''.join(f'<option value="{v}">{text}</option>' for v,text in options)+'</select></label>'
    def number(ident,label,value):return f'<label class="lab-field" for="{ident}">{label}<input type="number" min="0" step="any" id="{ident}" value="{value}"></label>'
    def box(ident,controls,label):return f'<div class="lab-box"><div class="scenario-options">{controls}</div><div class="lab-actions"><button type="button" data-action="{ident}">{label}</button></div><p class="lab-state" data-pass="info" id="{ident}-state" role="status" aria-live="polite">'+t('Ready — choose inputs','就绪 — 选择输入')+f'</p><div class="lab-output" id="{ident}-output"></div></div>'
    controls='<label class="lab-field" for="chain-message">'+t('Block 1 payload','区块 1 内容')+'<input type="text" maxlength="120" id="chain-message" value="Alice pays Bob 5"></label>'+select('chain-mode',t('How to handle later links','如何处理后续链接'),[('keep',t('Keep original later links','保留后续原链接')),('rebuild',t('Rebuild all later links','重建全部后续链接'))])
    body+=section('01 / HASH LINKS',t('Relinking a history does not authorize it','重新链接历史不等于授权历史'),t('Original payload: Alice pays Bob 5. Modify it and compare keeping versus rebuilding the later links. Blocks contain only an index, payload and prior digest.','原内容：Alice pays Bob 5。修改后比较保留与重建后续链接。区块仅包含编号、内容及前一个摘要。'),box('chain',controls,t('Compute the teaching chain','计算教学链'))+para(t('With original links, a changed first block breaks the next reference. If all later links are rebuilt, the toy history becomes internally consistent again; no consensus, signatures, difficulty or finality were checked. That distinction explains why a hash chain is not a full blockchain.','保留原链接时，第一区块改变会破坏下一引用。全部后续链接重建后，玩具历史可重新内部一致，但未检查共识、签名、难度或最终性。这解释了哈希链为何不是完整区块链。')),'chain')
    controls=number('allowance-balance',t('Owner balance · whole teaching units','所有者余额 · 整数教学单位'),'20')+number('allowance-limit',t('Approved amount · whole units','授权数量 · 整数单位'),'10')+number('allowance-spend',t('Requested transferFrom · whole units','请求 transferFrom · 整数单位'),'4')
    body+=section('02 / ERC-20',t('Both balance and authorization must permit a transfer','余额与授权都必须允许转移'),t('A simplified ordinary finite allowance with no token fees, hooks or special infinite allowance behavior.','简化普通有限授权，无代币费用、钩子或特殊无限授权行为。'),box('allowance',controls,t('Simulate the authorized transfer','模拟授权转移'))+para(t('The model computes the resulting owner balance, recipient increase and allowance. Try an amount exceeding allowance, then one exceeding balance. Failures leave all state unchanged. The real downloadable ERC-20 is tested on an EVM; this browser model is not a contract deployment.','模型计算所有者余额、接收方增加量及剩余额度。尝试超过额度，再尝试超过余额；失败保持所有状态不变。下载 ERC-20 已在 EVM 测试，此浏览器模型不是合约部署。')),'allowance')
    controls=number('amm-x',t('Reserve X · teaching tokens','储备 X · 教学代币'),'100')+number('amm-y',t('Reserve Y · teaching units','储备 Y · 教学单位'),'10000')+number('amm-input',t('Input X','输入 X'),'10')+select('amm-fee',t('Fee model','费用模型'),[('0.003','0.30%'),('0','0%')])+number('amm-min',t('Minimum output Y','最小输出 Y'),'900')
    body+=section('03 / DEFI',t('A swap changes the reserve ratio','兑换改变储备比例'),t('A constant-product, v2-style quote with fees retained in the pool. All numbers are synthetic, and the floating-point output is approximate.','v2 式恒定乘积报价，费用保留池内。数字均为合成，浮点输出为近似值。'),box('amm',controls,t('Inspect the AMM quote','检查 AMM 报价'))+code('effectiveInput = input × (1 − fee)\noutput = reserveY × effectiveInput / (reserveX + effectiveInput)\nnewX = reserveX + input\nnewY = reserveY − output')+para(t('If the computed output is below the selected minimum, the model rejects the swap and keeps the original reserves. It does not model other traders, MEV, token rounding, concentrated liquidity or live prices.','若计算输出低于最小值，模型拒绝兑换并保留原储备。它不模拟其他交易者、MEV、代币舍入、集中流动性或实时价格。'))+cite(lang,'uniswap','mev'),'amm')
    return body+'</div>'

def bundle():
    directory=ROOT/'examples'
    required=['package.json','package-lock.json','README.md','hardhat.config.ts','contracts/MessageBoard.sol','contracts/StudyToken.sol','scripts/compile.mjs','scripts/local.mjs','scripts/demo.mjs','test/contracts.test.mjs']
    with zipfile.ZipFile(ROOT/'examples.zip','w',compression=zipfile.ZIP_DEFLATED) as z:
        for name in required:
            path=directory/name
            info=zipfile.ZipInfo('blockchain-atlas-examples/'+name,(2026,10,1,0,0,0));info.compress_type=zipfile.ZIP_DEFLATED;info.external_attr=0o100644<<16
            z.writestr(info,path.read_bytes())

if __name__=='__main__':
    bundle()
    for lang in ('en','zh'):
        for page in PAGES:
            body=overview(lang) if page=='index' else tools_page(lang) if page=='tools' else sources_page(lang) if page=='sources' else labs_page(lang) if page=='labs' else chapter_page(page,lang)
            (ROOT/href(page,lang)).write_text(shell(lang,page,body),encoding='utf-8')
    print(f'Built {2*len(PAGES)} pages, {len(TOOLS)} resources, {DIAGRAM_COUNT} bilingual diagrams, 3 local labs, 2 contract examples')
